# Site settings
lang: en-US
title: My Awesome Site
email: athila.m.mattos@gmail.com
description: My Awesome Site Description
url: "https://binarydevotee.github.io"
author:
  name: Athila Mattos
github_username: binarydevotee

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.26.2
plugins:
  - mmistakes/minimal-mistakes@4.26.2
